debug_level: debug
store_dir: /var/lib/domain-health
log_file: /var/log/domain-health
listen_address: :4222
health_time: 600
connect_timeout: 10
subscribe_cert_warning: 2592000
subscribe_message_calm: 43200
subscriber:
  ding_talk:
    enable: false
    secret: ""
    web_hook: ""
fetcher:
  aliyun:
    enable: false
    region_id: ""
    access_key_id: ""
    access_key_secret: ""
    only_type:
      - "A"
    black_rr_list:
      - "@"
      - "^\\*."