version: "2"
services:
  domain-health:
    build: .
    image: domain-health
    volumes:
      - /var/lib/domain-health/config.local.yaml:/bin/config.local.yaml
      - /opt/domain-health/leveldb:/var/lib/domain-health/leveldb
    ports:
      - 4222:4222

